[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
build = "build.rs"
license = "Apache-2.0"
name = "sled-node"
version = "0.12.1"

[build-dependencies]
neon-build = "0.1.20"

[dependencies]
neon = "0.1.20"
sled = "0.13.0"

[lib]
crate-type = ["dylib"]
name = "sled_node"
