[package]
name = "rsdb-node"
version = "0.12.1"
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
license = "Apache-2.0"
build = "build.rs"

[lib]
name = "rsdb_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.20"

[dependencies]
neon = "0.1.20"
